[[plugins]]

package = "netlify-plugin-checklinks"
  [plugins.inputs]
  # checkExternal = true
  skipPatterns = [
    "main.css",
    "_site/feed.xml", # https://github.com/Munter/netlify-plugin-checklinks/issues/566
  ]
