[[plugins]]

package = "netlify-plugin-checklinks"
  [plugins.inputs]
  checkExternal = true
  skipPatterns = [
    "main.css",
    "_site/feed.xml",
  ]
  todoPatterns = [
    "content-type-missing",
    "https://github.com/numist/numi.st/blob/main/"
  ]
